# This is a basic workflow to help you get started with Actions

name: Compile beta html

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  buildHtml:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib --never install flixel 4.11.0
          haxelib install hxcpp
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-ui 2.4.0
          haxelib remove flixel-addons
          haxelib install flixel-addons 2.11.0
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib list
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build Project.xml html5 --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish to github Pages
        run: |
          cd export/release/html5/bin
          git init
          git add *
          git remote add origin https://Sylveondev:${{ secrets.TOKEN }}@github.com/sylveondev/pokehell-beta-web.git
          git config user.email a@a
          git config user.name a
          git commit -m "Gihub actions commit" --allow-empty
          git branch
          git show-ref
          git push origin master -f
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: htmlBuild
          path: 'export/release/html5/bin' 
  
